### ISSUE TITLE
Ghidra Parse error related to NSObject

### ISSUE THREAD

**Issue by fmagin** [PoomSmart/IDAObjcTypes#9]
Happens with commit c5bab42a0ab16c47215ce8e2fa650ba4518931f1 (current master)
```
C Parser: Encountered errors during parse. in /home/fmagin/gits/IDAObjcTypes/Darwin/../Foundation/../objc/Types.h near line -5678  Error: Undefined data type “NSObject”
    near token: null
Possibly Undefined : NSObject 
Last Valid Datatype: id
Check around CParserPlugin.out around line: 5698
```

Full CParserPlugin.out file is available at https://gist.github.com/fmagin/7856a8ee459d8e940902dd6fb6d63def

Line 5698 (+- 1) is:
```C
typedef struct Protocol {
    NSObject super;
} Protocol;
```

The typedef for `NSObject` happens later in line 5771 

```C
typedef struct NSObject {
    Class isa;
} NSObject;
```

Don't have time to investigate the issue right now, but I am currently trying to write some Ghidra Script to parse the repo into a GDT archive in the CI, which should catch those issues in the future.

**Comment by PoomSmart** [comment]
This is probably fixed as of https://github.com/PoomSmart/IDAObjcTypes/commit/b6afc226060138e5557f08e6506c90472f89cc45

**Comment by fmagin** [comment]
Yes, can confirm that b6afc226060138e5557f08e6506c90472f89cc45 fixed this. Thanks!
